export const CardResponseSchema = {
  type: 'object',
  properties: {
    accountId: { type: 'string' },
    user: { type: 'string' },
    laneId: { type: 'string' },
    name: { type: 'string' },
    amount: { type: 'number' },
    closedAt: { type: 'string' },
    attributes: { type: 'array' },
    updatedAt: { type: 'string' },
    createdAt: { type: 'string' },
    id: { type: 'string' },
  },
  required: [
    'accountId',
    'user',
    'laneId',
    'name',
    'updatedAt',
    'createdAt',
    'id',
  ],
  additionalProperties: false,
};
